"""Check an extracted Windows installer for the matching WebView2 SDK loader.

Usage: python scripts/verify-windows-loader.py <extracted-installer-directory>
The staging report is generated by Tauri's beforeBundleCommand.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import struct
import sys

ROOT = Path(__file__).resolve().parents[1]
MACHINES = {0x014C: "x86", 0x8664: "x64", 0xAA64: "arm64"}


def inspect_pe(path: Path) -> tuple[str, list[str]]:
    data = path.read_bytes()
    if len(data) < 64 or data[:2] != b"MZ":
        raise ValueError(f"Invalid Windows binary: {path.name}")
    pe = struct.unpack_from("<I", data, 0x3C)[0]
    if pe + 24 > len(data) or data[pe:pe + 4] != b"PE\0\0":
        raise ValueError(f"Invalid PE header: {path.name}")
    machine, section_count = struct.unpack_from("<HH", data, pe + 4)
    architecture = MACHINES.get(machine)
    if architecture is None:
        raise ValueError(f"Unsupported Windows machine: {machine:#x}")
    optional_size = struct.unpack_from("<H", data, pe + 20)[0]
    optional = pe + 24
    if optional + optional_size > len(data):
        raise ValueError("Truncated PE optional header")
    magic = struct.unpack_from("<H", data, optional)[0]
    if magic not in {0x10B, 0x20B}:
        raise ValueError("Unsupported PE optional header")
    directories = optional + (112 if magic == 0x20B else 96)
    import_rva = struct.unpack_from("<I", data, directories + 8)[0]
    sections = []
    for index in range(section_count):
        offset = optional + optional_size + 40 * index
        virtual_size, address, raw_size, raw_offset = struct.unpack_from("<IIII", data, offset + 8)
        sections.append((address, max(virtual_size, raw_size), raw_offset, raw_size))

    def file_offset(rva: int) -> int:
        for address, size, raw_offset, raw_size in sections:
            if address <= rva < address + size and rva - address < raw_size:
                result = raw_offset + rva - address
                if result < len(data):
                    return result
        raise ValueError("Invalid PE import address")

    imports = []
    if import_rva:
        offset = file_offset(import_rva)
        for _ in range(1024):
            descriptor = struct.unpack_from("<IIIII", data, offset)
            if not any(descriptor):
                break
            start = file_offset(descriptor[3])
            end = data.index(b"\0", start, min(start + 256, len(data)))
            imports.append(data[start:end].decode("ascii"))
            offset += 20
        else:
            raise ValueError("Unterminated PE import table")
    return architecture, imports


def verify(payload: Path) -> dict:
    host_arch, imports = inspect_pe(payload / "OpenNexus.exe")
    loader = payload / "WebView2Loader.dll"
    if not loader.is_file():
        raise ValueError("Installer is missing WebView2Loader.dll beside OpenNexus.exe")
    loader_arch, _ = inspect_pe(loader)
    if loader_arch != host_arch:
        raise ValueError(f"Loader architecture {loader_arch} does not match Host {host_arch}")
    expected = json.loads((ROOT / ".build/windows/webview2-loader.json").read_text(encoding="utf-8"))
    sha256 = hashlib.sha256(loader.read_bytes()).hexdigest()
    if expected["architecture"] != host_arch or expected["sha256"] != sha256:
        raise ValueError("Packaged Loader differs from the prepared, locked WebView2 SDK")
    return {"host_architecture": host_arch, "host_imports": imports,
            "loader_sha256": sha256, "loader_sdk_version": expected["version"]}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("payload", type=Path)
    args = parser.parse_args()
    try:
        print(json.dumps(verify(args.payload.resolve(strict=True)), indent=2))
    except (OSError, ValueError, KeyError, struct.error) as error:
        print(f"Windows package check failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
